### ISSUE TITLE
coref is broken with latest CoreNLP

### ISSUE THREAD

**Issue by dmnapolitano** [EducationalTestingService/stanford-thrift#29]
```java
2 [pool-1-thread-4] ERROR org.apache.thrift.ProcessFunction  - Internal error processing resolve_coreferences_in_trees
java.lang.NoSuchMethodError: edu.stanford.nlp.pipeline.ParserAnnotatorUtils.fillInParseAnnotations(ZZLedu/stanford/nlp/trees/GrammaticalStructureFactory;Ledu/stanford/nlp/util/CoreMap;Ledu/stanford/nlp/trees/Tree;)V
        at org.ets.research.nlp.stanford_thrift.general.CoreNLPThriftUtil.getAnnotationFromParseTrees(Unknown Source)
        at org.ets.research.nlp.stanford_thrift.StanfordCoreNLPHandler.resolve_coreferences_in_trees(Unknown Source)
        at CoreNLP.StanfordCoreNLP$Processor$resolve_coreferences_in_trees.getResult(Unknown Source)
        at CoreNLP.StanfordCoreNLP$Processor$resolve_coreferences_in_trees.getResult(Unknown Source)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:206)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
49775 [pool-1-thread-8] ERROR org.apache.thrift.ProcessFunction  - Internal error processing get_entities_from_text
java.lang.NoSuchMethodError: edu.stanford.nlp.pipeline.ParserAnnotatorUtils.fillInParseAnnotations(ZZLedu/stanford/nlp/trees/GrammaticalStructureFactory;Ledu/stanford/nlp/util/CoreMap;Ledu/stanford/nlp/trees/Tree;)V
        at org.ets.research.nlp.stanford_thrift.general.CoreNLPThriftUtil.getAnnotationFromParseTrees(Unknown Source)
        at org.ets.research.nlp.stanford_thrift.ner.StanfordNERThrift.getNamedEntitiesFromTrees(Unknown Source)
        at org.ets.research.nlp.stanford_thrift.StanfordCoreNLPHandler.get_entities_from_text(Unknown Source)
        at CoreNLP.StanfordCoreNLP$Processor$get_entities_from_text.getResult(Unknown Source)
        at CoreNLP.StanfordCoreNLP$Processor$get_entities_from_text.getResult(Unknown Source)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:206)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
7964998360 [pool-1-thread-9] ERROR org.apache.thrift.ProcessFunction  - Internal error processing resolve_coreferences_in_tokenized_sentences
java.lang.NoSuchMethodError: edu.stanford.nlp.pipeline.ParserAnnotatorUtils.fillInParseAnnotations(ZZLedu/stanford/nlp/trees/GrammaticalStructureFactory;Ledu/stanford/nlp/util/CoreMap;Ledu/stanford/nlp/trees/Tree;)V
        at org.ets.research.nlp.stanford_thrift.general.CoreNLPThriftUtil.getAnnotationFromParseTrees(Unknown Source)
        at org.ets.research.nlp.stanford_thrift.StanfordCoreNLPHandler.resolve_coreferences_in_tokenized_sentences(Unknown Source)
        at CoreNLP.StanfordCoreNLP$Processor$resolve_coreferences_in_tokenized_sentences.getResult(Unknown Source)
        at CoreNLP.StanfordCoreNLP$Processor$resolve_coreferences_in_tokenized_sentences.getResult(Unknown Source)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:206)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by willguo** [comment]
Hello Diane,

Hope you are doing well. I have been experimenting around with your CoreNLP/Thrift setup lately (thanks for all of your hard work!), and ran into issues with coref with the new Stanford CoreNLP, version 3.6.0. I thought I would submit an issue; but noticed that you had self-assigned this one a while back. Have you made any progress in regards to this issue since then? I am also currently working on isolating/debugging the problem for my own sake, but I thought I would reach out just in case.

Was a bit confused at the error tag: NoSuchMethodError, considering I believe fillInParseAnnotations() still exists as part of the pipeline. I had originally thought that maybe the function had been renamed, but it seems that this is not the case. I will continue to update this what I find in the meantime.

Cheers,
Will
